### ISSUE TITLE
documentation: add link to storybook somewhere on this repository's main page

### ISSUE THREAD

**Issue by hamirmahal** [tide-app/tide#192]
I think it would be convenient if somewhere on [the main page of this repository](https://github.com/amilajack/freesound-player) we had a link to this repository's storybook at https://amilajack.github.io/freesound-player.

**Comment by hamirmahal** [comment]
Maybe we can create a new section in [`README.md`](https://github.com/tide-app/tide/blob/master/README.md) that extracts
```bash
# Run storybook on your local machine
yarn storybook
# Deploy storybook to github pages
yarn deploy-storybook
```
from the "Setup" section.

We can change

> ## Setup
> 
> ```bash
> git clone https://github.com/tide-app/tide
> cd tide
> yarn
> yarn start
> 
> # Run storybook on your local machine
> yarn storybook
> # Deploy storybook to github pages
> yarn deploy-storybook
> 
> # E2E Tests
> yarn start
> # Run this in a separate terminal
> yarn cypress open
> ```
to
> ## Setup
> 
> ```bash
> git clone https://github.com/tide-app/tide
> cd tide
> yarn
> yarn start
> 
> # E2E Tests
> yarn start
> # Run this in a separate terminal
> yarn cypress open
> ```
> ## Storybook
> https://amilajack.github.io/freesound-player
> ```bash
> # Run storybook on your local machine
> yarn storybook
> # Deploy storybook to github pages
> yarn deploy-storybook
> ```
@akshara-sun, do you want to take this?

**Comment by amilajack** [comment]
Yea I agree that this is some good low hanging fruit. @akshara-sun this should just be a simple markdown change
